---
title: 'Attention in PD: AXCPT'
author: "Alexis Torres"
date: "2023-05-09"
output: html_document
---

```{r = Load Libraries}
# Load the required packages
library(tidyverse)
library(ggeasy)
```

```{r = Read Data, Data Transformation}
# Read in the data from a file and create a dataframe
  #trying to read the E-Merge in as a .txt is a nightmare--convert to .csv
data <- read.csv("data_merged/merged_AXCPT.csv")

# Label session and medication status, then reduce subject ID to 3 digit subject number
AXCPT <- data %>%
    mutate(subject = SubjectID) %>%
    mutate(medstatus = ifelse((str_detect(subject, "ON")), "1", (ifelse((str_detect(subject, "OFF")), "0", NA))),
           meds = ifelse((str_detect(subject, "ON")), "On Meds", (ifelse((str_detect(subject, "OFF")), "Off Meds", NA))),
           session = ifelse((str_detect(subject, "v1")), "1", (ifelse((str_detect(subject, "v2")), "2", NA)))) %>%
      mutate(subject = substring(subject, 5, 7),
             CueAcc = CueSlide.ACC,
             CueRT = CueSlide.RT,
             ProbeAcc = ProbeSlide.ACC,
             ProbeRT = ProbeSlide.RT,
             TrialAcc = TrialACC,
             Cue = ifelse((str_detect(TrialType, "A")), "A", (ifelse((str_detect(TrialType, "B")), "B", NA))),
             Probe = ifelse((str_detect(TrialType, "X")), "X", (ifelse((str_detect(TrialType, "Y")), "Y", ifelse((str_detect(TrialType, "ng")), "ng", NA)))))

# Select the relevant columns, then eliminate practice trials, trials with missing values/breaks (26, 51, 76), and participants who did not complete both sessions (003, 005)
AXCPT <- AXCPT %>%
  select(subject, session, medstatus, meds, Block, Trial, TrialType, Cue, Probe, CueAcc, CueRT, ProbeAcc, ProbeRT, TrialAcc) %>%
  filter(Trial != 1, Trial != 2, Trial != 3, Trial != "NA", Trial != 26, Trial != 51, Trial != 76) %>%
  filter(subject != "003", subject != "005")

```

https://sites.wustl.edu/dualmechanisms/ax-cpt-task/
```{r = Compute Behavioral Measures: d' Context Index}
# d' Context: This computes the signal detection d' measure selectively for AX and BX trial types (i.e., AX hits vs. BX false alarms).  The d' context measure reflects the ability of the participants to use contextual information from the cue to drive their answer on the probe--it indicates the ability to discriminate target and non-targets based on the cue.
#d′ context  index  is  calculated  by  computing  a d′index  from hits on AX trials and false alarms on BX trials as Z(H)−Z(F), with H representing hits on AX trials, F representing false alarms on BX trials, and Z representing the z-transform of a value. This measure reflects the ability of the participants to use contextual information from the cue to drive their answer on the probe

  # A higher d' context value indicates a better ability to discriminate between target and non-target stimuli based on the cue, while a lower value suggests a lower discriminability. In general, a positive d' context value indicates a relatively higher sensitivity in detecting the target stimulus compared to false alarms, suggesting a good ability to use the cue to differentiate target and non-target trials. On the other hand, a negative or near-zero d' context value suggests a lower sensitivity or more difficulty in discriminating between target and non-target stimuli based on the cue.



# Filter the AXCPT data for AX and BX trials
AXCPT_AXBX <- AXCPT %>%
  filter(TrialType %in% c("AX", "BX"))

# Calculate d-prime at the subject level
AXCPT_sDPrime <- AXCPT_AXBX %>%
  group_by(subject, medstatus, meds) %>%
  summarize(AXHits = sum(TrialAcc == 1 & TrialType == "AX"), 
            BXFalseAlarms = sum(ProbeAcc == 0 & CueAcc == 1 & TrialType == "BX"),
            AXTrials = sum(TrialType == "AX"),
            BXTrials = sum(TrialType == "BX"))
# Apply log-linear correction to error rates
AXCPT_sDPrime <- AXCPT_sDPrime %>%
  mutate(AXErrors = AXTrials - AXHits,
         BXErrors = BXFalseAlarms,
         AXErrorRate = (AXErrors + 0.5) / (AXTrials + 1),
         AXHitRate = (AXHits - 0.5) / (AXTrials + 1), # Hit rate for AX trials and linear transformation
         BXErrorRate = (BXErrors + 0.5) / (BXTrials + 1),# False alarm rate for BX trials
         AXZ = qnorm(AXHitRate),          # Z-transformed hit rate for AX trials
         BXZ = qnorm(BXErrorRate),          # Z-transformed false alarm rate for BX trials
         dprime = AXZ - BXZ)                # d' context index with log-linear corrected error rates

# Calculate d-prime at the condition level
AXCPT_DPrime <- AXCPT_AXBX %>%
  ungroup() %>%
  group_by(medstatus, meds) %>%
  summarize(AXHits = sum(CueAcc == 1 & ProbeAcc == 1 & TrialType == "AX"),
            BXFalseAlarms = sum(CueAcc == 1 & ProbeAcc == 0 & TrialType == "BX"),
            AXTrials = sum(TrialType == "AX"),
            BXTrials = sum(TrialType == "BX"))
# Apply log-linear correction to error rates
AXCPT_DPrime <- AXCPT_DPrime %>%
  mutate(AXErrors = AXTrials - AXHits,
         BXErrors = BXFalseAlarms,
         AXErrorRate = (AXErrors + 0.5) / (AXTrials + 1),
         AXHitRate = (AXHits - 0.5) / (AXTrials + 1), # Hit rate for AX trials an linear transformation
         BXErrorRate = (BXErrors + 0.5) / (BXTrials + 1),# False alarm rate for BX trials
         AXZ = qnorm(AXHitRate),          # Z-transformed hit rate for AX trials
         BXZ = qnorm(BXErrorRate),          # Z-transformed false alarm rate for BX trials
         dprime = AXZ - BXZ)                # d prime context index with log-linear corrected error rates

summary(AXCPT_sDPrime)

# Visualize the d-Prime
ggplot(AXCPT_sDPrime, aes(x = medstatus, y = dprime, color = subject, fill = subject, group = subject)) +
  geom_point(linewidth = 3, alpha = 0.7) +
  geom_line(linewidth = 1, alpha = 0.8) +
  labs(y = "\nd' Context (z-score)\n", x = '\nMedication Status', color = "Subject ID", fill = "Subject ID")+
  theme_bw() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  theme_classic(base_size = 16) +
  scale_x_discrete(breaks = 0:1, labels = c("Off Meds", "On Meds")) +
  #theme(legend.position = "none")+
  #theme(legend.title = element_blank())+
  ggtitle("\nSubject-Level d' Context Index in AX-CPT") +
  ggeasy::easy_center_title()

ggplot(AXCPT_DPrime, aes(x = medstatus, y = dprime, group = 1)) +
  geom_point(aes(fill = meds), color = "black", shape = 21, size = 4) +
  geom_line(color = "black", size = 1, alpha = 0.7) +
  labs(y = "\nd' Context (z-score)\n", x = "\nMedication Status") +
  theme_bw() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  theme_classic(base_size = 16) +
  scale_fill_manual(values = c("darkmagenta", "deepskyblue")) +
  scale_x_discrete(breaks = 0:1, labels = c("Off Meds", "On Meds")) +
  theme(legend.position = "none") +
  theme(legend.title = element_blank()) +
  guides(fill = guide_legend(title = "Medication \nStatus")) +
  ggtitle("\nd' Context Index in AX-CPT\n") +
  ggeasy::easy_center_title()


#Create a data file for data analysis in JASP.
  #For this file, you need one column for: subject ID, on med d', and off med d'
AXCPT_dprimeOn <- AXCPT_sDPrime %>%
  group_by(subject, medstatus) %>%
  mutate(OnMeds = ifelse(medstatus == 1, dprime, NA))%>%
  filter(OnMeds != 'NA') %>%
  ungroup() %>%
  select(subject, OnMeds)

AXCPT_dprimeOff <- AXCPT_sDPrime %>%
  group_by(subject, medstatus) %>%
  mutate(OffMeds = ifelse(medstatus == 0, dprime, NA))%>%
  filter(OffMeds != 'NA') %>%
  ungroup() %>%
  select(subject, OffMeds)

AXCPT_dprime <- full_join(AXCPT_dprimeOff, AXCPT_dprimeOn)

write_csv(AXCPT_dprime, "AXCPT_dprime.csv")

```

```{r = Compute Behavioral Measures: A-Cue Bias}
# For the AX-CPT, we are interested in:
  # A-Cue Bias: Signal detection bias for AX and AY trial types. The A-cue bias measure indicates the general tendency to make a target response following an A-cue (which would lead to a high AX target hit rate, but also a high AY false alarm rate).  Positive values indicate a positive bias, and are predicted to increase in proactive conditions in the DMC framework.
  #An  A-cue  bias  measure  was  also  calculated(Richmond et al., 2015) by computing a c criterion from hits on AX trials and false alarms on AY trials as 1/2*(Z[H]+Z[F]), with H representing hits on AX trials and F representing false alarms on AY trials.

  #If the A-cue bias is close to 0: It suggests that the participant's responses to A cues and non-A cues are relatively balanced, indicating a neutral or unbiased response pattern.
  #If the A-cue bias is positive: It suggests a bias towards responding to A cues more frequently than non-A cues. This could indicate a tendency to be more sensitive or more likely to respond when presented with A cues.
  #If the A-cue bias is negative: It suggests a bias against responding to A cues compared to non-A cues. This could indicate a tendency to be less sensitive or less likely to respond when presented with A cues.

# Filter the AXCPT data for AX and AY trials
AXCPT_AXAY <- AXCPT %>%
  filter(TrialType %in% c("AX", "AY"))

# Calculate A-cue bias at the subject level
AXCPT_sACueBias <- AXCPT_AXAY %>%
  group_by(subject, medstatus) %>%
  summarize(AXHits = sum(CueAcc == 1 & ProbeAcc == 1 & TrialType == "AX"),
            AYFalseAlarms = sum(CueAcc == 1 & ProbeAcc == 0 & TrialType == "AY"),
            AXTrials = sum(TrialType == "AX") + 1, # Laplace smoothing
            AYTrials = sum(TrialType == "AY") + 1) # Laplace smoothing
AXCPT_sACueBias <-AXCPT_sACueBias %>%
  mutate(AYFalseAlarms = AYFalseAlarms + 0.5,  # Laplace smoothing
         AXHits = AXHits + 0.5, # Laplace smoothing
         AXZ = qnorm(AXHits / AXTrials),
         AYZ = qnorm(AYFalseAlarms / AYTrials),
         ACueBias = 0.5 * (AXZ + AYZ))

# Calculate A-cue bias at the condition level
AXCPT_ACueBias <- AXCPT_AXAY %>%
  group_by(medstatus, meds) %>%
  summarize(AXHits = sum(CueAcc == 1 & ProbeAcc == 1 & TrialType == "AX"),
            AYFalseAlarms = sum(CueAcc == 1 & ProbeAcc == 0 & TrialType == "AY"),
            AXTrials = sum(TrialType == "AX") + 1,# Laplace smoothing
            AYTrials = sum(TrialType == "AY") + 1)# Laplace smoothing
AXCPT_ACueBias <-AXCPT_ACueBias %>%
  mutate(AYFalseAlarms = AYFalseAlarms + 0.5,  # Laplace smoothing
         AXHits = AXHits + 0.5, # Laplace smoothing
         AXZ = qnorm(AXHits / AXTrials),
         AYZ = qnorm(AYFalseAlarms / AYTrials),
         ACueBias = 0.5 * (AXZ + AYZ))


# Visualize the A-cue bias
ggplot(AXCPT_sACueBias, aes(x = medstatus, y = ACueBias, color = subject, fill = subject, group = subject)) +
  geom_point(linewidth = 3, alpha = 0.7) +
  geom_line(linewidth = 1, alpha = 0.8) +
  labs(y = '\nA-Cue Bias\n', x = '\nMedication Status', color = "Subject ID", fill = "Subject ID")+
  theme_bw() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  theme_classic(base_size = 16) +
  scale_x_discrete(breaks = 0:1, labels = c("Off Meds", "On Meds")) +
  #theme(legend.position = "none")+
  #theme(legend.title = element_blank())+
  ggtitle("\nSubject-Level A-Cue Bias in AX-CPT") +
  ggeasy::easy_center_title()

ggplot(AXCPT_ACueBias, aes(x = medstatus, y = ACueBias, group = 1)) +
  geom_point(aes(fill = meds), color = "black", shape = 21, size = 4) +
  geom_line(color = "black", size = 1, alpha = 0.7) +
  labs(y = '\nA-Cue Bias\n', x = '\nMedication Status') +
  theme_bw() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  theme_classic(base_size = 16) +
  scale_fill_manual(values = c("darkmagenta", "deepskyblue")) +
  scale_x_discrete(breaks = 0:1, labels = c("Off Meds", "On Meds")) +
  theme(legend.position = "none") +
  theme(legend.title = element_blank()) +
  guides(fill = guide_legend(title = "Medication \nStatus")) +
  ggtitle("\nA-Cue Bias in AX-CPT\n") +
  ggeasy::easy_center_title()

#Create a data file for data analysis in JASP.
  #For this file, you need one column for: subject ID, on med a-cue bias, and off med a-cue bias
AXCPT_ABiasOn <- AXCPT_sACueBias %>%
  group_by(subject, medstatus) %>%
  mutate(OnMeds = ifelse(medstatus == 1, ACueBias, NA))%>%
  filter(OnMeds != 'NA') %>%
  ungroup() %>%
  select(subject, OnMeds)

AXCPT_ABiasOff <- AXCPT_sACueBias %>%
  group_by(subject, medstatus) %>%
  mutate(OffMeds = ifelse(medstatus == 0, ACueBias, NA))%>%
  filter(OffMeds != 'NA') %>%
  ungroup() %>%
  select(subject, OffMeds)

AXCPT_ACueBiasIndex <- full_join(AXCPT_ABiasOff, AXCPT_ABiasOn)

write_csv(AXCPT_ACueBiasIndex, "AXCPT_ACueBias.csv")

```

```{r = Compute Behavioral Measures: Proactive Behavioral Index}
# Proactive Behavioral Index: This computes a normalized difference score of performance distinctions between AY and BX trial types (i.e., [AY-BX]/[AY+BX]).   It can be computed on both RT and accuracy measures as well as their sum.  This  index reflects the relative balance of interference between AY and BX trials:  a  positive  PBI  reflects  higher  interference  on  AY  trials, indicating  proactive  control,  whereas  a  negative  PBI  reflects higher interference on BX trials, indicating reactive control.
#Gonthier et al : The PBI  was  computed  separately  for  error  rates  (based  on  average error rates on AY and BX trials) and for RTs (based on average RTs on AY and BX trials); a composite PBI was also computed by  averaging  the  PBIs  obtained  for  error  rates  and  RTs  after standardization. The standardization was performed by using the average and standard deviation calculated over both conditions of the AX-CPT to allow for comparison between the two.

AXCPT_AYBX <- AXCPT %>%
  filter(TrialType %in% c("AY", "BX"))

#Calculate the PBI for error rates at the subject level
AXCPT_sAYBX <- AXCPT_AYBX %>%
  group_by(subject, medstatus, meds) %>%
  summarize(AYFalseAlarms = sum(CueAcc == 1 & ProbeAcc == 0 & TrialType == "AY"),
            BXFalseAlarms = sum(CueAcc == 1 & ProbeAcc == 0 & TrialType == "BX"),
            AYTrials = sum(TrialType == "AY"),
            BXTrials = sum(TrialType == "BX"),
            AYRT = mean(ProbeRT[TrialType == "AY"]),
            BXRT = mean(ProbeRT[TrialType == "BX"]))%>%
  mutate(AYFalseAlarms = AYFalseAlarms + 0.5, # Laplace smoothing
         BXFalseAlarms = BXFalseAlarms + 0.5) # Laplace smoothing
AXCPT_sPBI <- AXCPT_sAYBX %>%
  group_by(subject, medstatus, meds) %>%
  mutate(AYErrors = sum(AYTrials * AYFalseAlarms),
            BXErrors = sum(BXTrials * BXFalseAlarms)) %>%
  mutate(erPBI = (AYErrors - BXErrors) / (AYTrials + BXTrials),
         rtPBI = (AYRT - BXRT) / (AYRT + BXRT))
# Standardize PBIs and compute composite PBI
AXCPT_ssPBI <- AXCPT_sPBI %>%
  ungroup() %>%
  mutate(rtPBI = ifelse(rtPBI == 'NaN', 0.0000, rtPBI)) %>%
  mutate(mean_erPBI = mean(erPBI),
         sd_erPBI = sd(erPBI),
         mean_rtPBI = mean(rtPBI),
         sd_rtPBI = sd(rtPBI))
AXCPT_ssPBI <- AXCPT_ssPBI %>%
  mutate(serPBI = (erPBI - mean_erPBI)/sd_erPBI,
         srtPBI = (rtPBI - mean_rtPBI)/sd_rtPBI) %>%
  mutate(composite_PBI = (serPBI + srtPBI)/2)

#Calculate the PBI for error rates at the condition level
AXCPT_AYBX <- AXCPT_AYBX %>%
  group_by(medstatus, meds) %>%
  summarize(AYFalseAlarms = sum(CueAcc == 1 & ProbeAcc == 0 & TrialType == "AY"),
            BXFalseAlarms = sum(CueAcc == 1 & ProbeAcc == 0 & TrialType == "BX"),
            AYTrials = sum(TrialType == "AY"),
            BXTrials = sum(TrialType == "BX"),
            AYRT = mean(ProbeRT[TrialType == "AY"]),
            BXRT = mean(ProbeRT[TrialType == "BX"]))%>%
  mutate(AYFalseAlarms = AYFalseAlarms + 0.5, # Laplace smoothing
         BXFalseAlarms = BXFalseAlarms + 0.5) # Laplace smoothing

AXCPT_PBI <- AXCPT_AYBX %>%
  group_by(medstatus, meds) %>%
  mutate(AYErrors = sum(AYTrials * AYFalseAlarms),
            BXErrors = sum(BXTrials * BXFalseAlarms)) %>%
  mutate(erPBI = (AYErrors - BXErrors) / (AYTrials + BXTrials),
         rtPBI = (AYRT - BXRT) / (AYRT + BXRT))

# Standardize PBIs and compute composite PBI
AXCPT_sPBI <- AXCPT_PBI %>%
  ungroup() %>%
  mutate(rtPBI = ifelse(rtPBI == 'NaN', 0.0000, rtPBI)) %>%
  mutate(mean_erPBI = mean(erPBI),
         sd_erPBI = sd(erPBI),
         mean_rtPBI = mean(rtPBI),
         sd_rtPBI = sd(rtPBI))
AXCPT_sPBI <- AXCPT_sPBI %>%
  mutate(serPBI = (erPBI - mean_erPBI)/sd_erPBI,
         srtPBI = (rtPBI - mean_rtPBI)/sd_rtPBI) %>%
  mutate(composite_PBI = (serPBI + srtPBI)/2)



# Visualize the PBI
ggplot(AXCPT_ssPBI, aes(x = medstatus, y = composite_PBI, color = subject, fill = subject, group = subject)) +
  geom_point(linewidth = 3, alpha = 0.7) +
  geom_line(linewidth = 1, alpha = 0.8) +
  labs(y = '\nComposite PBI\n(Standardized Error Rate & RT)', x = '\nMedication Status', color = "Subject ID", fill = "Subject ID")+
  theme_bw() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  theme_classic(base_size = 16) +
  scale_x_discrete(breaks = 0:1, labels = c("Off Meds", "On Meds")) +
  #theme(legend.position = "none")+
  #theme(legend.title = element_blank())+
  ggtitle("\nSubject-Level Proactive Behavioral Index in AX-CPT") +
  ggeasy::easy_center_title()

ggplot(AXCPT_sPBI, aes(x = medstatus, y = composite_PBI, group = 1)) +
  geom_point(aes(fill = meds), color = "black", shape = 21, size = 4) +
  geom_line(color = "black", size = 1, alpha = 0.7) +
  labs(y = '\nComposite PBI\n(Standardized Error Rate & RT)', x = '\nMedication Status') +
  theme_bw() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  theme_classic(base_size = 16) +
  scale_fill_manual(values = c("darkmagenta", "deepskyblue")) +
  scale_x_discrete(breaks = 0:1, labels = c("Off Meds", "On Meds")) +
  theme(legend.position = "none") +
  theme(legend.title = element_blank()) +
  guides(fill = guide_legend(title = "Medication \nStatus")) +
  ggtitle("\nProactive Behavioral Index in AX-CPT\n") +
  ggeasy::easy_center_title()



#Create a data file for data analysis in JASP.
  #For this file, you need one column for: subject ID, on med PBI, and off med PBI
AXCPT_PBIOn <- AXCPT_ssPBI %>%
  group_by(subject, medstatus) %>%
  mutate(OnMeds_cPBI = ifelse(medstatus == 1, composite_PBI, NA),
         OnMeds_erPBI = ifelse(medstatus == 1, erPBI, NA),
         OnMeds_rtPBI = ifelse(medstatus == 1, rtPBI, NA))%>%
  filter(OnMeds_cPBI != 'NA',
         OnMeds_erPBI != 'NA',
         OnMeds_rtPBI != 'NA') %>%
  ungroup() %>%
  select(subject, OnMeds_cPBI, OnMeds_erPBI, OnMeds_rtPBI)

AXCPT_PBIOff <- AXCPT_ssPBI %>%
  group_by(subject, medstatus) %>%
  mutate(OffMeds_cPBI = ifelse(medstatus == 0, composite_PBI, NA),
         OffMeds_erPBI = ifelse(medstatus == 0, erPBI, NA),
         OffMeds_rtPBI = ifelse(medstatus == 0, rtPBI, NA))%>%
  filter(OffMeds_cPBI != 'NA',
         OffMeds_erPBI != 'NA',
         OffMeds_rtPBI != 'NA') %>%
  ungroup() %>%
  select(subject, OffMeds_cPBI, OffMeds_erPBI, OffMeds_rtPBI)

AXCPT_PBIndex <- full_join(AXCPT_PBIOff, AXCPT_PBIOn)

write_csv(AXCPT_PBIndex, "AXCPT_PBIndex.csv")
```


